modLoader="javafml"
loaderVersion="[47,)"
license="GNU GPLv3"
issueTrackerURL="https://github.com/skyjay1/Nomadic-Tents/issues"

[[mods]]
    modId="nomadictents"
    version="20.1.0"
    displayName="Nomadic Tents"
    description='''Adds portable houses to Minecraft!'''
    [[dependencies.nomadictents]]
        modId="forge"
        mandatory=true
        versionRange="[47.3,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.nomadictents]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.20.1,]"
        ordering="NONE"
        side="BOTH"